In [1]:
#文件不能不能命名为中文？否则打不开文件
import pandas as pd
import numpy as np


In [2]:
#加载数据
dataset = pd.read_csv('../datasets/50_Startups.csv')
X = dataset.iloc[:,:-2].to_numpy()
#类别数据
X1 = dataset.iloc[:,3].to_numpy()
Y = dataset.iloc[:, 4].to_numpy()
print("部分数据X")
print(X[0:5,:])
print("部分数据Y")
print(Y[0:5])

部分数据X
[[165349.2  136897.8  471784.1 ]
 [162597.7  151377.59 443898.53]
 [153441.51 101145.55 407934.54]
 [144372.41 118671.85 383199.62]
 [142107.34  91391.77 366168.42]]
部分数据Y
[192261.83 191792.06 191050.39 182901.99 166187.94]


In [3]:
#类别数据数字化
#oneHotEncoder:热编码，虚拟变量，用于反映事物类型的数据(非数值数据)，且没有大小之分。如男女可表示为 10 、 01  红黄绿分别表示为 100 010 001 
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder = LabelEncoder()
X1= labelencoder.fit_transform(X1[:])
onehotencoder = OneHotEncoder()
X1 = onehotencoder.fit_transform(X1.reshape(-1,1)).toarray()
print("地区代码热编码：")
print(X1)

地区代码热编码：
[[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]


In [4]:
#特征合并
X = np.concatenate((X,X1),axis=1)
#躲避虚拟变量陷阱：通过前两个变量我就能预测到第三个变量，如我知道前两个为 0 1 则下一个虚拟变量一定为0
X = X[:,:-1]
#X = X.astype(np.float32)
#Y = Y.astype(np.float32)
print("部分数据X")
print(X[0:5,:])
print("部分数据Y")
print(Y[0:5])

部分数据X
[[1.6534920e+05 1.3689780e+05 4.7178410e+05 0.0000000e+00 0.0000000e+00]
 [1.6259770e+05 1.5137759e+05 4.4389853e+05 1.0000000e+00 0.0000000e+00]
 [1.5344151e+05 1.0114555e+05 4.0793454e+05 0.0000000e+00 1.0000000e+00]
 [1.4437241e+05 1.1867185e+05 3.8319962e+05 0.0000000e+00 0.0000000e+00]
 [1.4210734e+05 9.1391770e+04 3.6616842e+05 0.0000000e+00 1.0000000e+00]]
部分数据Y
[192261.83 191792.06 191050.39 182901.99 166187.94]


In [5]:
#拆分数据集和测试集
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2,random_state=0)

In [6]:
#训练模型
from sklearn.linear_model import LinearRegression
regressor = LinearRegression(normalize=True)
regressor.fit(X_train,Y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=True)

In [7]:
#预测结果
y_pred = regressor.predict(X_test)

In [8]:
#评估结果
from sklearn.metrics import mean_absolute_error
mean_absolute_error(Y_test,y_pred)

7514.293659640612

In [9]:
regressor.coef_

array([ 7.73467193e-01,  3.28845975e-02,  3.66100259e-02, -6.99369053e+02,
       -1.65865321e+03])